apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly-iii-application
  namespace: argocd
spec:
  project: app-project
  source:
    repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
    targetRevision: HEAD
    path: firefly-iii
  destination:
    server: "https://kubernetes.default.svc"
    namespace: firefly-iii
  syncPolicy:
    automated:
      prune: true