# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: immich-psql
#   name: immich-psql
#   namespace: immich
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: immich-psql
#   template:
#     metadata:
#       labels:
#         app: immich-psql
#     spec:
#       containers:
#       - envFrom:
#         - configMapRef:
#             name: immich-psql-cm
#         - secretRef:
#             name: immich-psql-secret
#         image: ghcr.io/tensorchord/cloudnative-vectorchord:17.7
#         imagePullPolicy: IfNotPresent
#         name: immich-psql
#         ports:
#         - containerPort: 5432
#           protocol: TCP
#         volumeMounts:
#         - mountPath: /var/lib/postgresql/data
#           subPath: data
#           name: immich-psql-data
#       volumes:
#       - persistentVolumeClaim:
#           claimName: immich-psql
#         name: immich-psql-data
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
spec:
  instances: 1

  storage:
    size: 1Gi

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    initdb:
      # TODO: Use managed extensions (pg 18)
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;