apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: iot-project
  source:
    repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
    targetRevision: HEAD
    path: home-assistant
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homeassistant
  syncPolicy:
    automated:
      prune: true