---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unpackerr
  name: unpackerr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unpackerr
  template:
    metadata:
      labels:
        app: unpackerr
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: unpackerr-cm
        - secretRef:
            name: unpackerr-secret
        image: golift/unpackerr:latest
        imagePullPolicy: Always
        name: unpackerr
        volumeMounts:
        - mountPath: /data/downloads
          name: downloads
      volumes:
        - name: downloads
          nfs:
            server: 10.0.0.100
            path: /volume1/media/downloads
      securityContext:
        runAsUser: 1024
        runAsGroup: 100