# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: radarr
#   name: radarr
#   namespace: servarr
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: radarr
#   template:
#     metadata:
#       labels:
#         app: radarr
#     spec:
#       containers:
#       - envFrom:
#         - configMapRef:
#             name: radarr-cm
#         image: lscr.io/linuxserver/radarr:latest
#         imagePullPolicy: Always
#         name: radarr
#         ports:
#         - containerPort: 7878
#           protocol: TCP
#         volumeMounts:
#         - mountPath: /config
#           name: radarr-config
#         - mountPath: /data
#           name: media
#       volumes:
#         - persistentVolumeClaim:
#             claimName: radarr
#           name: radarr-config
#         - name: media
#           nfs:
#             server: 10.0.0.100
#             path: /volume1/media