---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true # Enable host network mode.
      dnsPolicy: ClusterFirstWithHostNet # Ensure the pod can resolve domain names in the cluster.
      containers:
      - image: ghcr.io/home-assistant/home-assistant:stable
        envFrom:
        - configMapRef:
            name: homeassistant-cm
        imagePullPolicy: Always
        name: homeassistant
        ports:
        - containerPort: 8123
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: homeassistant-config
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /run/dbus
          name: dbus
          readOnly: true
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
      - image: codercom/code-server
        imagePullPolicy: Always 
        name: code-server
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: code-server-secret
        volumeMounts:
          - mountPath: /home/coder/home-assistant
            name: homeassistant-config
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      - image:  ghcr.io/esphome/esphome
        imagePullPolicy: Always
        name: esphome
        envFrom:
          - configMapRef:
              name: esphome-cm
          - secretRef:
              name: esphome-secret
        volumeMounts:
        - mountPath: /config
          name: esphome-config
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
      volumes:
        - persistentVolumeClaim:
            claimName: homeassistant
          name: homeassistant-config
        - persistentVolumeClaim:
            claimName: esphome
          name: esphome-config
        - hostPath:
            path: /etc/localtime
          name: localtime
        - hostPath: 
            path: /run/dbus
          name: dbus
        