---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true # Enable host network mode.
      dnsPolicy: ClusterFirstWithHostNet # Ensure the pod can resolve domain names in the cluster.
      containers:
      - image: ghcr.io/home-assistant/home-assistant:stable
        envFrom:
        - configMapRef:
            name: homeassistant-cm
        imagePullPolicy: Always
        name: homeassistant
        ports:
        - containerPort: 8123
          protocol: TCP
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "6Gi"
            cpu: "2000m"
        volumeMounts:
        - mountPath: /config
          name: homeassistant-config
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /run/dbus
          name: dbus
          readOnly: true
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
      - image: lscr.io/linuxserver/code-server:latest
        imagePullPolicy: Always 
        name: code-server
        ports:
        - containerPort: 8443
        envFrom:
          - secretRef:
              name: code-server-secret
          - configMapRef:
              name: code-server-cm
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /home/coder/home-assistant
            name: homeassistant-config
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      - image:  ghcr.io/esphome/esphome
        imagePullPolicy: Always
        name: esphome
        envFrom:
          - configMapRef:
              name: esphome-cm
          - secretRef:
              name: esphome-secret
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /config
          name: esphome-config
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
      - image: eclipse-mosquitto
        imagePullPolicy: Always
        name: mosquitto
        ports:
          - containerPort: 1883
          - containerPort: 9001
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /mosquitto
          name: mosquitto
      - image: ghcr.io/koenkk/zigbee2mqtt
        imagePullPolicy: Always
        name: zigbee2mqtt
        envFrom:
        - configMapRef:
            name: zigbee2mqtt-cm
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /app/data
          name: zigbee2mqtt-data
        - mountPath: /run/udev
          name: udev
          readOnly: true
      volumes:
        - persistentVolumeClaim:
            claimName: homeassistant
          name: homeassistant-config
        - persistentVolumeClaim:
            claimName: esphome
          name: esphome-config
        - persistentVolumeClaim:
            claimName: zigbee2mqtt
          name: zigbee2mqtt-data
        - persistentVolumeClaim:
            claimName: mosquitto
          name: mosquitto
        - hostPath:
            path: /etc/localtime
          name: localtime
        - hostPath: 
            path: /run/dbus
          name: dbus
        - hostPath:
            path: /run/udev
          name: udev
        