---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: homeassistant
  namespace: homeassistant
  labels:
    app.kubernetes.io/name: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homeassistant.monroe.gg`)
      priority: 10
      services:
        - kind: Service
          name: homeassistant
          namespace: homeassistant
          port: 8123
    - kind: Rule
      match: Host(`homeassistant-code.monroe.gg`)
      priority: 10
      services:
        - kind: Service
          name: homeassistant
          port: 8443
    - kind: Rule
      match: Host(`esphome.monroe.gg`)
      priority: 10
      services:
        - kind: Service
          name: homeassistant
          port: 6052
    - kind: Rule
      match: Host(`z2m.monroe.gg`)
      priority: 10
      services:
        - kind: Service
          name: homeassistant
          port: 8081
  tls:
    certResolver: porkbun