apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: networking-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Project for networking related applications
  destinations:
  - namespace: networking
    server: https://kubernetes.default.svc
  - namespace: pihole
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/Monroeshindelar/kubernetes-manifests
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
