apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: filesystem-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Project for filesystem applications
  destinations:
  - namespace: filesystem
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: longhorn-system
    server: https://kubernetes.default.svc
    name: in-cluster
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'