apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cs2-server-application
  namespace: argocd
spec:
  project: game-server-project
  source:
    repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
    targetRevision: HEAD
    path: cs2-server
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cs
  syncPolicy:
    automated:
      prune: true