apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unpackerr-application
  namespace: argocd
spec:
  project: servarr-project
  source:
    repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
    targetRevision: HEAD
    path: unpackerr
  destination:
    server: "https://kubernetes.default.svc"
    namespace: servarr
  syncPolicy:
    automated:
      prune: true