apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: media-project
  sources:
    - chart: immich
      repoURL: oci://ghcr.io/immich-app/immich-charts/immich
      targetRevision: 0.10.3
      helm:
        valueFiles:
          - $git/immich/charts/values.yaml
    - repoURL: https://github.com/Monroeshindelar/kubernetes-manifests.git
      targetRevision: HEAD
      path: immich/resources
      ref: git
  destination:
    server: "https://kubernetes.default.svc"
    namespace: immich
  syncPolicy:
    automated:
      prune: true