apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: servarr-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for iot related applications
  destinations:
  - namespace: servarr
    server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
