---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr
  namespace: servarr
  labels:
    app.kubernetes.io/instance: traefik-networking
    app.kubernetes.io/name: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`bazarr.monroe.gg`)
      priority: 10
      services:
        - name: bazarr
          port: 6767
    - kind: Rule
      match: Host(`bazarr.monroeshindelar.com`)
      priority: 10
      services:
        - name: bazarr
          port: 6767
  tls:
    certResolver: porkbun